<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], []],
    '_wdt' => [['token'], ['_controller' => 'web_profiler.controller.profiler::toolbarAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_wdt']], [], []],
    '_profiler_home' => [[], ['_controller' => 'web_profiler.controller.profiler::homeAction'], [], [['text', '/_profiler/']], [], []],
    '_profiler_search' => [[], ['_controller' => 'web_profiler.controller.profiler::searchAction'], [], [['text', '/_profiler/search']], [], []],
    '_profiler_search_bar' => [[], ['_controller' => 'web_profiler.controller.profiler::searchBarAction'], [], [['text', '/_profiler/search_bar']], [], []],
    '_profiler_phpinfo' => [[], ['_controller' => 'web_profiler.controller.profiler::phpinfoAction'], [], [['text', '/_profiler/phpinfo']], [], []],
    '_profiler_search_results' => [['token'], ['_controller' => 'web_profiler.controller.profiler::searchResultsAction'], [], [['text', '/search/results'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_open_file' => [[], ['_controller' => 'web_profiler.controller.profiler::openAction'], [], [['text', '/_profiler/open']], [], []],
    '_profiler' => [['token'], ['_controller' => 'web_profiler.controller.profiler::panelAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_router' => [['token'], ['_controller' => 'web_profiler.controller.router::panelAction'], [], [['text', '/router'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_exception' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::body'], [], [['text', '/exception'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_exception_css' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::stylesheet'], [], [['text', '/exception.css'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    'admin_empresa' => [[], ['_controller' => 'App\\Controller\\Admin\\AdminEmpresaController::index'], [], [['text', '/admin/empresa']], [], []],
    'admin_empresa_modif' => [['id'], ['_controller' => 'App\\Controller\\Admin\\AdminEmpresaController::admin_empresa_modif'], ['id' => '\\d+'], [['variable', '/', '\\d+', 'id', true], ['text', '/admin/empresa']], [], []],
    'admin_empresa_elim' => [['id'], ['_controller' => 'App\\Controller\\Admin\\AdminEmpresaController::admin_empresa_elim'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/admin/empresa/elim']], [], []],
    'newEmpresa' => [[], ['_controller' => 'App\\Controller\\Admin\\AdminEmpresaController::new_empresa'], [], [['text', '/admin/empresa/add']], [], []],
    'admin_oferta' => [[], ['_controller' => 'App\\Controller\\Admin\\AdminOfertaController::index'], [], [['text', '/admin/oferta']], [], []],
    'admin_oferta_modif' => [['id'], ['_controller' => 'App\\Controller\\Admin\\AdminOfertaController::admin_oferta_modif'], ['id' => '\\d+'], [['variable', '/', '\\d+', 'id', true], ['text', '/admin/oferta']], [], []],
    'admin_oferta_elim' => [['id'], ['_controller' => 'App\\Controller\\Admin\\AdminOfertaController::admin_oferta_elim'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/admin/oferta/elim']], [], []],
    'newOferta' => [[], ['_controller' => 'App\\Controller\\Admin\\AdminOfertaController::newOferta'], [], [['text', '/admin/oferta/add']], [], []],
    'empreses' => [[], ['_controller' => 'App\\Controller\\EmpresaController::index'], [], [['text', '/empreses']], [], []],
    'empresa' => [['id'], ['_controller' => 'App\\Controller\\EmpresaController::detallEmpresa'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/empreses']], [], []],
    'ofertes' => [[], ['_controller' => 'App\\Controller\\OfertaController::index'], [], [['text', '/']], [], []],
    'oferta' => [['id'], ['_controller' => 'App\\Controller\\OfertaController::detalleOferta'], [], [['variable', '/', '[^/]++', 'id', true]], [], []],
];
